[package]
name = "codegen"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
convert_case = "0.6.0"
prettyplease = "0.2.20"
proc-macro2 = "1"
project-root = "0.2.2"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = "2"
